ib:
  host: localhost
  port: 7497

logging:
  level: DEBUG

fastapi:
  title: IBKR Web API
  description: RESTful API for accessing Interactive Brokers historical market data
  version: "1.0"
  docs_url: /docs
  redoc_url: /redoc
  openapi_url: /openapi.json
  debug: false

uvicorn:
  host: "127.0.0.1"
  port: 8000